// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNt1nMqa78_jFmqYRo7HJOdHs-eeSQtzI',
    appId: '1:609723965758:web:d9f043352e23d4eca00c6f',
    messagingSenderId: '609723965758',
    projectId: 'hamro-taxi-e4239',
    authDomain: 'hamro-taxi-e4239.firebaseapp.com',
    databaseURL: 'https://hamro-taxi-e4239-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamro-taxi-e4239.appspot.com',
    measurementId: 'G-W1HHGLZEJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlXyKMk6z_lWhh2b9GaD_tDA9vaCgCD4',
    appId: '1:609723965758:android:8cf51c10854b0161a00c6f',
    messagingSenderId: '609723965758',
    projectId: 'hamro-taxi-e4239',
    databaseURL: 'https://hamro-taxi-e4239-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamro-taxi-e4239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5yApxPUoL5qOrZpK84FR07PifwVf_RE',
    appId: '1:609723965758:ios:d775d9bca349503ca00c6f',
    messagingSenderId: '609723965758',
    projectId: 'hamro-taxi-e4239',
    databaseURL: 'https://hamro-taxi-e4239-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamro-taxi-e4239.appspot.com',
    iosClientId: '609723965758-3npfie3mma9qvqdeb3c3apo13vaktofv.apps.googleusercontent.com',
    iosBundleId: 'com.example.h',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC5yApxPUoL5qOrZpK84FR07PifwVf_RE',
    appId: '1:609723965758:ios:5b05494864d144b5a00c6f',
    messagingSenderId: '609723965758',
    projectId: 'hamro-taxi-e4239',
    databaseURL: 'https://hamro-taxi-e4239-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamro-taxi-e4239.appspot.com',
    iosClientId: '609723965758-4nl0fo0gasr9gvelt8vna4bqer0lhpvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamroTaxi',
  );
}
